##properties
server:
  port: 9001

spring:
    # DATASOURCE
    datasource:
        name: druidDataSource
        url: jdbc:mysql://192.168.0.10:4408/mob_ad?useUnicode=true&characterEncoding=utf-8
        username: root
        password: mobcb
        # 使用druid数据源
        driverClassName: com.mysql.jdbc.Driver
#mybatis config
mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.mobcb.deji.entity
  mapper-locations: classpath*:mappers/*.xml

