server:
  port: 9999

#multipart:
#  enabled: true
spring:
  http:
    multipart:
      enabled: true
      maxFileSize: 50Mb
      maxRequestSize: 60Mb
#      location: /

  cloud:
    loadbalancer:
      retry:
        enabled: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
